[package]
name = "bathbot-cache"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bb8-redis = { version = "0.12" }
eyre = { version = "0.6" }
itoa = { version = "1.0" }
once_cell = { version = "1.0" }
rkyv = { version = "0.7" }
tracing = { version = "0.1" }
twilight-model = { workspace = true }
twilight-gateway = { workspace = true }