[package]
name = "bathbot-util"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = { version = "0.6" }
once_cell = { version = "1.0" }
regex = { version = "1.0" }
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "next", features = ["cache", "metrics", "rkyv"] }
time = { version = "0.3", features = ["parsing"] }
twilight-model = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv-13", default-features = false }